/*eslint-env browser*/
/*globals xsltforms_d0 XsltForms_browser XsltForms_engine xsltforms_initImpl XsltForms_subform XsltForms_model XsltForms_instance*/
"use strict";
/**
 * @author Alain Couthures <alain.couthures@agencexml.com>
 * @licence LGPL - See file 'LICENSE.md' in this project.
 * @module in_script
 * @description /**'''XSLTForms Javascript for insertion in script elements'''
 */

if (typeof xsltforms_d0 === "undefined") {
	(function () {
		if (![].slice.call(document.styleSheets).some(
			function(elt) {
				return elt.href.indexOf("xsltforms2.css") !== -1;
			}
		)) {
			var root = [].slice.call(document.getElementsByTagName("script")).filter(
				function (elt) {
					return elt.src.indexOf("xsltforms2.js") !== -1;
				})[0].src.replace("xsltforms2.js", "");
			if (root.substr(root.length - 4, 4) === "/js/") {
				root = root.substr(0, root.length - 3) + "css/";
			}
			var newelt;
			newelt = document.createElement("link");
			newelt.setAttribute("rel", "stylesheet");
			newelt.setAttribute("type", "text/css");
			newelt.setAttribute("href", root + "xsltforms2.css");
			document.getElementsByTagName("head")[0].appendChild(newelt);
		}
		var addLoadListener = function(func) {
			if (window.addEventListener) {
				window.addEventListener("load", func, false);
			} else if (document.addEventListener) {
				document.addEventListener("load", func, false);
			} else if (window.attachEvent) {
				window.attachEvent("onload", func);
			} else if (typeof window.onload !== "function") {
				window.onload = func;
			} else {
				var oldonload = window.onload;
				window.onload = function() {
					oldonload();
					func();
				};
			}
		};
		var xsltforms_initImpl = function () {
			if (!(document.documentElement.childNodes[0].nodeType === 8 || (XsltForms_browser.isIE && document.documentElement.childNodes[0].childNodes[1] && document.documentElement.childNodes[0].childNodes[1].nodeType === 8))) {
				var comment = document.createComment("HTML elements and Javascript instructions generated by XSLTForms $$$VersionName$$$ ($$$VersionNumber$$$) - Copyright (C) $$$VersionYear$$$ <agenceXML> - Alain Couthures - http://www.agencexml.com");
				document.documentElement.insertBefore(comment, document.documentElement.firstChild);
			}
			[].concat.apply([],
				[].slice.call(document.getElementsByTagName("xforms-engine")).map(
					function (elt) {
						return [].slice.call(elt.attributes);
					}
				)
			).forEach(
				function (attr) {
					XsltForms_engine.conf[attr.name.toLowerCase()] = attr.value;
				}
			);
			XsltForms_engine.debugMode = XsltForms_engine.conf.debug === "true";
			XsltForms_engine.mainform = document.createElement("xforms-subform");
			XsltForms_engine.mainform.id = "xsltforms-mainform";
			document.body.insertBefore(XsltForms_engine.mainform, document.body.firstChild);
			XsltForms_engine.create.subform(null, XsltForms_engine.mainform);
			var conselt = document.createElement("div");
			conselt.setAttribute("id", "xsltforms_console");
			document.body.appendChild(conselt);
			conselt = document.createElement("div");
			conselt.setAttribute("id", "statusPanel");
			conselt.setAttribute("style", "display: none; z-index: 99; top: 294.5px; left: 490px;");
			conselt.innerHTML = XsltForms_engine.conf.loadingmsg;
			document.body.appendChild(conselt);
			XsltForms_browser.dialog.show('statusPanel');
			if (XsltForms_engine.debugMode) {
				XsltForms_engine.debugging();
			}
			[].slice.call(document.getElementsByTagName("xforms-model")).forEach(
				function (model, index) {
					if (model.id === "xsltforms-mainform-model-config") {
						return;
					}
					if (!model.id) {
						model.id = XsltForms_engine.mainform.id + (index === 0 ? "-model-default" : "-model-" + XsltForms_engine.mainform.counters.model);
					}
					XsltForms_engine.create.model(XsltForms_engine.mainform, model);
					[].slice.call(model.children).map(
						function(elt) {
							return [elt].concat(elt.nodeName.toLowerCase().split("-", 2))
								.reduce(
									function(result, item, index) {
										result[["instance", "ns", "name"][index]] = item;
										return result;
									}
								, {});
						}
					).filter(
						function(o) {
							return o.ns === "xforms" && o.name !== "" && o.name !== null && XsltForms_engine.create[o.name] !== null;
						}
					).forEach(
						function(o, index) {
							if (!o.instance.id) {
								o.instance.id = XsltForms_engine.mainform.id + (index === 0 ? "-instance-default" : "-instance-" + XsltForms_engine.mainform.counters.instance);
							}
							XsltForms_engine.create[o.name](XsltForms_engine.mainform, o.instance);
						}
					);
				}
			);
			var modelt = document.getElementById("xsltforms-mainform-model-config");
			var instelt;
			if (!modelt) {
				modelt = document.createElement("xforms-model");
				modelt.setAttribute("id", "xsltforms-mainform-model-config");
				document.getElementsByTagName("body")[0].appendChild(modelt);
				instelt = document.createElement("xforms-instance");
				instelt.setAttribute("id", "xsltforms-mainform-instance-config");
				modelt.appendChild(instelt);
				var scriptelt = document.createElement("script");
				scriptelt.setAttribute("type", "text/plain");
				scriptelt.textContent = "<properties><language>navigator</language></properties>";
				instelt.appendChild(scriptelt);
			} else {
				instelt = document.getElementById("xsltforms-mainform-instance-config");
			}
			XsltForms_engine.create.model(XsltForms_engine.mainform, modelt);
			XsltForms_engine.create.instance(XsltForms_engine.mainform, instelt);
			XsltForms_browser.config = instelt.doc.documentElement;
			XsltForms_browser.idPf = XsltForms_engine.mainform.id + "-";
			XsltForms_browser.i18n.asyncinit(XsltForms_engine.init);
		};
		var xsltforms_init = function () {
			try {
				xsltforms_initImpl();
			} catch(e) {
				alert("XSLTForms Exception\n--------------------------\n\n"+(typeof(e.stack)==="undefined"?"":e.stack)+"\n\n"+(e.name?e.name+(e.message?"\n\n"+e.message:""):e));
			}
		};
		if (document.readyState === "complete") {
			xsltforms_init();
		} else {
			addLoadListener(xsltforms_init);
		}
	})();
}